// Generated by gencpp from file neuvition_driver/test.msg
// DO NOT EDIT!


#ifndef NEUVITION_DRIVER_MESSAGE_TEST_H
#define NEUVITION_DRIVER_MESSAGE_TEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace neuvition_driver
{
template <class ContainerAllocator>
struct test_
{
  typedef test_<ContainerAllocator> Type;

  test_()
    : data()  {
    }
  test_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::neuvition_driver::test_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neuvition_driver::test_<ContainerAllocator> const> ConstPtr;

}; // struct test_

typedef ::neuvition_driver::test_<std::allocator<void> > test;

typedef boost::shared_ptr< ::neuvition_driver::test > testPtr;
typedef boost::shared_ptr< ::neuvition_driver::test const> testConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neuvition_driver::test_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neuvition_driver::test_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::neuvition_driver::test_<ContainerAllocator1> & lhs, const ::neuvition_driver::test_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::neuvition_driver::test_<ContainerAllocator1> & lhs, const ::neuvition_driver::test_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace neuvition_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::neuvition_driver::test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neuvition_driver::test_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neuvition_driver::test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neuvition_driver::test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neuvition_driver::test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neuvition_driver::test_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neuvition_driver::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79cd2e4a60f8fd7afcb0476d2ea77fdc";
  }

  static const char* value(const ::neuvition_driver::test_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79cd2e4a60f8fd7aULL;
  static const uint64_t static_value2 = 0xfcb0476d2ea77fdcULL;
};

template<class ContainerAllocator>
struct DataType< ::neuvition_driver::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neuvition_driver/test";
  }

  static const char* value(const ::neuvition_driver::test_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neuvition_driver::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] data\n"
;
  }

  static const char* value(const ::neuvition_driver::test_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neuvition_driver::test_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neuvition_driver::test_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neuvition_driver::test_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEUVITION_DRIVER_MESSAGE_TEST_H
